[keifererikson.nightfox.info]
version = "0.0.14"
hash = "sha256-EZGKJMc/N+0V+9U/k12tUbzgfCNzWhdrouXRi7QOdyY="

[keifererikson.nightfox.meta]
description = "A foxy theme for Visual Studio Code"
homepage = "https://github.com/keifererikson/vscode-nightfox.git"
license = "MIT"


[willasm.comment-highlighter.info]
version = "2.1.1"
hash = "sha256-gGHoDL4NJB2hCrlPP3yp4t2UN+8AIN3s04T8LYyvt/Y="

[willasm.comment-highlighter.meta]
description = "Colorful Comment Highlighter for Visual Studio Code"
homepage = "https://github.com/willasm/comment-highlighter#readme"
license = "MIT"
