[LeonardSSH.vscord.info]
version = "5.3.8"
hash = "sha256-tqyhu6pa+UFwCYpS3xioeSw4oET0TFfQmJ8hsSz3q/k="

[LeonardSSH.vscord.meta]
description = "Highly customizable Discord Rich Presence extension for Visual Studio Code"
homepage = "https://github.com/LeonardSSH/vscord"
license = "MIT"


[Catppuccin.catppuccin-vsc-icons.info]
version = "1.26.0"
hash = "sha256-V1ZhNtCouo0EDrblvoZsiMy7BPPSGdOn5SoZl4kA/z0="

[Catppuccin.catppuccin-vsc-icons.meta]
description = "Catppuccin Icons for VSCode/VSCodium"
homepage = "https://github.com/catppuccin/vscode-icons.git"
license = "MIT"


[keifererikson.nightfox.info]
version = "0.0.14"
hash = "sha256-EZGKJMc/N+0V+9U/k12tUbzgfCNzWhdrouXRi7QOdyY="

[keifererikson.nightfox.meta]
description = "A foxy theme for Visual Studio Code"
homepage = "https://github.com/keifererikson/vscode-nightfox.git"
license = "MIT"


[willasm.comment-highlighter.info]
version = "2.1.1"
hash = "sha256-gGHoDL4NJB2hCrlPP3yp4t2UN+8AIN3s04T8LYyvt/Y="

[willasm.comment-highlighter.meta]
description = "Colorful Comment Highlighter for Visual Studio Code"
homepage = "https://github.com/willasm/comment-highlighter#readme"
license = "MIT"


[geequlim.godot-tools.info]
version = "2.5.1"
hash = "sha256-kAzRSNZw1zaECblJv7NzXnE2JXSy9hzdT2cGX+uwleY="

[geequlim.godot-tools.meta]
description = "Game development tools for working with Godot Engine in Visual Studio Code"
homepage = "https://github.com/godotengine/godot-vscode-plugin#readme"
license = "MIT"


[vadimcn.vscode-lldb.info]
version = "1.12.0"
hash = "sha256-pHVoFTm2UaXCjGhDNBIbFsfjJc1GB+ugNeSsPSULthQ="

[vadimcn.vscode-lldb.meta]
description = "A native debugger extension for VSCode based on LLDB"
homepage = "https://github.com/vadimcn/codelldb"
license = "MIT"
